### PR TITLE
feat(api): dump profile data through http request

### PR DESCRIPTION
**Pull request by zeroqn**
**What this PR does / why we need it**:

This PR integrated [pprof-rs](https://github.com/nervosnetwork/muta/pull/438) into ```core-api``` through
configuration ```enable_dump_profile```.

Usage example:
```shell
curl http://127.0.0.1:8000/dump_profile\?duration=30\&\&report=flamegraph > flamegraph.svg
```
Or go pprof support
```shell
curl http://127.0.0.1:8000/dump_profile\?duration=30\&\&report=pprof > profile.pb
pprof -svg profile.pb
```

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #
https://github.com/nervosnetwork/muta-docs/pull/64

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yejiayu** [comment]
How about opening this feature with a configuration file?

**Comment by zeroqn** [comment]
> How about opening this feature with a configuration file?

Ok, seems more convenience.

**Comment by yejiayu** [comment]
Update muta docs @zeroqn

**Comment by zeroqn** [comment]
> Update muta docs @zeroqn

Done

**Pull request merged**
