### PR TITLE
fix: load hrp before deserializing genesis payload to take hrp effect

### PR DESCRIPTION
**Pull request by LycrusHamster**
**What this PR does / why we need it**:

fix: load hrp before deserializing genesis payload to take hrp effect

**Which docs this PR relation**:

N/A

**Which toolchain this PR adaption**:

N/A

No Breaking Change

**Special notes for your reviewer**:

This is an internal bug and fix doesn't take any changes to toolchains and docs.

hrp should load firstly before deserializing genesis cause Address maybe in service genesis payload may need hrp

### CODE REVIEW

**Comment by yejiayu** [comment]
We should add unit test for this PR which avoid running failures due to some breaking changes in future

**Comment by LycrusHamster** [comment]
> We should add unit test for this PR which avoid running failures due to some breaking changes in future

So as I think. The problem is not to add test, but where to add?

**Comment by yejiayu** [comment]
> > We should add unit test for this PR which avoid running failures due to some breaking changes in future
> 
> 
> 
> So as I think. The problem is not to add test, but where to add?

The point of testing is to match field, so i think it's just a matter of ensuring that the serialized Metadata json string can read the fields.

Can we add it to types/metadata.rs？

**Comment by LycrusHamster** [comment]
> > > We should add unit test for this PR which avoid running failures due to some breaking changes in future
> > 
> > 
> > So as I think. The problem is not to add test, but where to add?
> 
> The point of testing is to match field, so i think it's just a matter of ensuring that the serialized Metadata json string can read the fields.
> 
> Can we add it to types/metadata.rs？

The hrp can only be set once, which means if I set hrp to sth. like 'meow', the following address's hrp have to be 'meow'
However cargo test is designed to run parelly and each test case must not relate to others.
I don't wan't to set test thread to 1.
And if I set hrp, other tests shall fail.

Thus.....you see the 'crippled' test cases...

**Pull request merged**
